- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      - zypper:
        update_cache: yes
        name: '*'
        state: latest
      changed_when: False
  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/cron.yml
