- name: Download Oh-My-Zsh installer
  get_url: url=https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh dest=/tmp/ohmyzshinstall.sh

- name: Execute Oh-My-Zsh installer
  shell: /tmp/ohmyzshinstall.sh

# - name: Remove Oh-My-Zsh installer
  # file: path=/tmp/ohmyzshinstall.sh state=absent