- name: Download Oh-My-Zsh installer
  get_url: url=https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh dest=/tmp/ohmyzshinstall.sh

- name: Execute Oh-My-Zsh installer
  shell: /tmp/ohmyzshinstall.sh
 
- name: Configure Oh-My-Zsh theme
  replace:
    path: /home/tj/.zshrc
    regexp: 'ZSH_THEME=.*'
    replace: 'ZSH_THEME=agnoster'
 
- name: Configure Oh-My-Zsh theme
  replace:
    path: /home/tj/.zshrc
    regexp: 'plugins=(.*)'
    replace: 'plugins=(git thefuck'
 
- name: Set default shell
   become: yes
   user:
     name: 'tj'
     shell: /bin/zsh

# - name: Remove Oh-My-Zsh installer
  # file: path=/tmp/ohmyzshinstall.sh state=absent