- name: Copy wallpaper file
  copy: src=files/wallpaper.jpg dest=/home/tj/.wallpaper.jpg
 
- name: Install dependencies
  pip:
    name: argparse
    executable: pip3

- name: Copy wallpaper script
  copy: src=utilities/plasma_wallpaper_changer.py dest=/home/tj/.plasma_wallpaper_changer.py

- name: Run Py script to change wallapaper
  raw: python3 /home/tj/.plasma_wallpaper_changer.py /home/tj/.wallapaper.jpg
  args:
    executable: /bin/bash