- name: Copy wallpaper file
  copy: src=files/wallpaper.jpg dest=/home/tj/.wallpaper.jpg
 
- name: Install dependencies
  pip:
    name: argparse
    executable: pip3

- name: Copy wallpaper file
  copy: src=/utilities/plasma_wallpaper_changer.py dest=/home/tj/.utilities/plasma_wallpaper_changer.py owner=tj group=tj mode=600

- name: Run Py script to change wallapaper
  script: /home/tj/.utilities/plasma_wallpaper_changer.pyy /home/tj/.wallapaper.jpg
  args:
    executable: python3