- name: Copy wallpaper file
  copy: src=files/wallpaper.jpg dest=/home/tj/.wallpaper.jpg owner=tj group=tj mode=600
 
- name: Install dependencies
  pip:
    name: argparse
    executable: pip3

- name: Run Py script to change wallapaper
  command: /utilities/plasma_wallpaper_changer.py /home/tj/.wallapaper.jpg
  executable: python3