- name: Copy wallpaper file
  copy: src=files/wallpaper.jpg dest=/home/tj/.wallpaper.jpg

- name: Configure Wallpaper (will apply after reboot)
  replace:
    path: /home/tj/.config/plasma-org.pde.plasma.desktop-appletsrc
    regexp: 'Image=.*(jpg|png)'
    replace: 'Image=file:///home/tj/.wallpaper.jpg'
    when: (ansible_facts['distribution'] == "OpenSUSE")